function result = calculate_VIRT_design_v3(Pv_max, w_height, h_core_max, T_tx_max, ...
    R_plate, Area_plate, T_water, sig_grease, d_grease, params)

    %% Flux Density
    Bmax = (Pv_max / (params.k * params.f ^ params.alpha))^(1 / params.beta);

    %% Core Geometry
    % Square wave voltage with amplitude Vso generated across sum of
    % primaries for nt tracks
    Vso = params.Np * params.nt * params.Vo;

    % For a peak triangular flux density, the minimum core area required is:
    Ac = Vso / (4 * params.f * params.Np * Bmax);

    % Air gap on center leg
    % For nt tracks in series, total inductance is nt*Lu
    lg = params.u0 * params.Np^2 * Ac / (params.nt * params.Lu);

    % Square centerpost
    w_core = sqrt(Ac); % Since this is a square, both length and width are fixed

    % Outer legs: area = 1/2 center post area => uniform B in all sections
    l_leg  = 0.5 * Ac / w_core;

    % Yoke
    h_yoke = l_leg;

    % Core dimensions
    l_core = 2 * w_height + 2 * l_leg + w_core;
    h_core = 2 * h_yoke + params.w_b;

    %% Absolute height constraint
    if h_core > h_core_max
        result = struct( ...
            'is_valid',      false, ...
            'fail_reason',   'h_core exceeds h_core_max', ...
            'Bmax',          NaN, ...
            'Ac',            NaN, ...
            'w_core',        NaN, ...
            'l_leg',         NaN, ...
            'h_yoke',        NaN, ...
            'l_core',        NaN, ...
            'h_core',        h_core, ...
            'w_b',           params.w_b, ...
            'l_winding',     NaN, ...
            'w_winding',     NaN, ...
            'V_total',       NaN, ...
            'A_footprint',   NaN, ...
            'lg',            NaN, ...
            'Rdc_pri',       NaN, ...
            'Rdc_sec',       NaN, ...
            'P_core',        NaN, ...
            'P_pri',         NaN, ...
            'P_sec',         NaN, ...
            'P_total',       NaN, ...
            'T_tx',          NaN ...
        );
        return;
    end

    %% Winding Geometry
    l_winding = w_core + 2 * w_height;
    w_winding = w_core + params.w_scale * 2 * w_height;

    %% Core Areas
    A_centerpost = w_core^2;
    A_leg        = l_leg  * w_core;
    A_yoke       = h_yoke * w_core;
    A_footprint  = w_winding * l_core;

    %% Core Volumes
    V_centerpost = A_centerpost * params.w_b;
    V_legs       = 2 * A_leg  * params.w_b;
    V_yokes      = 2 * A_yoke * l_core;
    V_total      = V_centerpost + V_legs + V_yokes;

    %% Core Loss
    P_core = V_total * params.k * params.f^params.alpha * Bmax^params.beta;

    %% DC Resistance
    Rdc_pri = calculate_Rdc_summation(100, ...
        w_core, l_winding, ...
        w_core, w_winding, ...
        params.sigma_cu, params.t_cu_pri);

    Rdc_sec = calculate_Rdc_summation(100, ...
        w_core, l_winding, ...
        w_core, w_winding, ...
        params.sigma_cu, params.t_cu_sec);

    %% AC Copper Loss
    [P_pri, P_sec] = calculate_Pcond( ...
        params.I, params.f, ...
        Rdc_pri, Rdc_sec, ...
        params.t_cu_pri, params.t_cu_sec, ...
        params.rho_cu, params.u0, params.stackup);

    %% Total Loss
    P_total = P_core + P_pri + P_sec;

    %% Temperature
    T_tx = calculate_transformer_temp( ...
        P_total, ...        % total dissipation
        Ac, ...             % center post area
        h_core/2, ...       
        R_plate, ...
        Area_plate, ...
        T_water, ...
        sig_grease, ...
        d_grease);

    %% Temperature constraint
    if T_tx > T_tx_max
        result = struct( ...
            'is_valid',      false, ...
            'fail_reason',   'T_tx exceeds T_tx_max', ...
            'Bmax',          NaN, ...
            'Ac',            Ac, ...
            'w_core',        w_core, ...
            'l_leg',         l_leg, ...
            'h_yoke',        h_yoke, ...
            'l_core',        l_core, ...
            'h_core',        h_core, ...
            'w_b',           params.w_b, ...
            'l_winding',     l_winding, ...
            'w_winding',     w_winding, ...
            'V_total',       V_total, ...
            'A_footprint',   A_footprint, ...
            'lg',            lg, ...
            'Rdc_pri',       Rdc_pri, ...
            'Rdc_sec',       Rdc_sec, ...
            'P_core',        P_core, ...
            'P_pri',         P_pri, ...
            'P_sec',         P_sec, ...
            'P_total',       NaN, ...
            'T_tx',          T_tx ...
        );
        return;
    end

    %% Package Results
    result = struct( ...
        'is_valid',      true, ...
        'fail_reason',   '', ...
        'Bmax',          Bmax, ...
        'Ac',            Ac, ...
        'w_core',        w_core, ...
        'l_leg',         l_leg, ...
        'h_yoke',        h_yoke, ...
        'l_core',        l_core, ...
        'h_core',        h_core, ...
        'w_b',           params.w_b, ...
        'l_winding',     l_winding, ...
        'w_winding',     w_winding, ...
        'V_total',       V_total, ...
        'A_footprint',   A_footprint, ...
        'lg',            lg, ...
        'Rdc_pri',       Rdc_pri, ...
        'Rdc_sec',       Rdc_sec, ...
        'P_core',        P_core, ...
        'P_pri',         P_pri, ...
        'P_sec',         P_sec, ...
        'P_total',       P_total, ...
        'T_tx',          T_tx ...
    );

end