% Generate an E Core Design for a 1/2-Turn VIRT
%
% Author:  Julia Estrin
% Date:    02-12-2026
% Updated: 02-27-2026 - Corrected calculation for core area and air gap
% Updated: 03-20-2026 - Added thermal limit (Qijia) 
% Updated: 03-27-2026 - Select round vs square centerpost/winding
%                     - Shape-dependent Rdc calculation
%
% Description:
%   Designs an E-core planar transformer for a 1/2-turn VIRT topology.
%   Given a maximum core loss density and window height, this function
%   computes all core and winding geometry, then evaluates core loss and
%   AC copper loss (via Dowell's method) to return a fully characterized
%   design result.
%
%   Core geometry assumptions:
%     - Outer leg area = 1/2 center post area  =>  uniform B across all sections
%     - Yoke area = leg area  =>  h_yoke = l_leg
%     - Center Leg gap
%   Magnetic circuit model (updated 02-27-2026):
%     - Square wave voltage Vso = Np * nt * Vo generated across primaries
%     - Peak triangular flux: Ac = Vso / (4 * f * Np * Bmax)
%     - Air gap: lg = u0 * Np^2 * Ac / (nt * Lu)
%     - Factor nt accounts for tracks in series
%
% Inputs:
%   Pv_max    - Maximum allowable core loss density [W/m^3]
%   w_height  - Winding window height [m]
%   params    - Parameter struct with fields:
%                 .k        - Steinmetz coefficient k  (P = k * B^beta)
%                 .beta     - Steinmetz exponent beta
%                 .Lu       - Inductance requirement per track [H]
%                 .I        - Peak winding current [A]
%                 .Np       - Number of primary turns
%                 .nt       - Number of secondary tracks
%                 .Vo       - Output voltage per track [V]
%                 .w_b      - Winding breadth (window width) [m]
%                 .f        - Switching frequency [Hz]
%                 .sigma_cu - Copper electrical conductivity [S/m]
%                 .rho_cu   - Copper electrical resistivity [Ohm·m]
%                 .t_cu_pri - Primary copper trace thickness [m]
%                 .t_cu_sec - Secondary copper trace thickness [m]
%                 .u0       - Permeability of free space [H/m]
%                 .stackup  - Winding stackup configuration string
%                 .centerpost_shape - Center post geometry: 'round' or 'square' (default: 'square')
%
% Outputs:
%   result    - Struct containing all design variables and losses:
%                 .Bmax         - Peak flux density [T]
%                 .Ac           - Required center leg cross-section area [m^2]
%                 .r_centerpost - Center post radius [m]
%                 .w_core       - Core width (= center post diameter) [m]
%                 .l_leg        - Outer leg length [m]
%                 .h_yoke       - Yoke height (= l_leg) [m]
%                 .l_core       - Total core length [m]
%                 .h_core       - Total core height [m]
%                 .w_b          - Winding window breadth/depth [m]
%                 .l_winding    - Winding outer dimension, length [m]
%                 .w_winding    - Winding outer dimension, width [m]
%                 .V_total      - Total core volume [m^3]
%                 .A_footprint  - PCB footprint area [m^2]
%                 .lg           - Air gap length per outer leg [m]
%                 .P_core       - Core loss [W]
%                 .Rdc_pri      - Primary DC winding resistance [Ohm]
%                 .Rdc_sec      - Secondary DC winding resistance [Ohm]
%                 .P_pri        - Primary AC conduction loss [W]
%                 .P_sec        - Secondary AC conduction loss [W]
%                 .P_total      - Total loss (core + primary + secondary) [W]
%                 .Cps          - Primary-to-secondary parasitic capacitance [F]




function result = calculate_VIRT_design(Pv_max, w_height, h_core_max, T_tx_max, ...
    R_plate, Area_plate, T_water, sig_grease, d_grease, params)

    if params.topology == "Multitrack"
        params.I = 2*params.I;
    end 

    % Input Validation
    if isfield(params, 'centerpost_shape')
        centerpost_shape = params.centerpost_shape;
    else
        centerpost_shape = 'square';  % Default to square (original behavior)
    end
    
    centerpost_shape = lower(centerpost_shape);
    if ~ismember(centerpost_shape, {'round', 'square'})
        error('centerpost_shape must be ''round'' or ''square''');
    end

    %% Flux Density
    Bmax = (Pv_max / (params.k * params.f ^ params.alpha))^(1 / params.beta);

    %% Core Geometry
    % Square wave voltage with amplitude Vso generated across sum of
    % primaries for nt tracks
    Vso = params.Np * params.nt * params.Vo;

    % For a peak triangular flux density, the minimum core area required is:
    Ac = Vso / (4 * params.f * params.Np * Bmax);

    % Air gap on center leg
    % For nt tracks in series, total inductance is nt*Lu
    lg = params.u0 * params.Np^2 * Ac / (params.nt * params.Lu);

    %% Centerpost Geometry (shape-dependent)
    if strcmp(centerpost_shape, 'round')
        % Round (cylindrical) centerpost
        r_centerpost = sqrt(Ac / pi);              % [m] center post radius
        w_core       = 2 * r_centerpost;           % [m] core width = center post diameter
    else
        % Square centerpost
        r_centerpost = NaN;                        % Not applicable for square
        w_core       = sqrt(Ac);                   % [m] core width = side length
    end

    % Outer legs: area = 1/2 center post area => uniform B in all sections
    l_leg  = 0.5 * Ac / w_core;

    % Yoke
    h_yoke = l_leg;

    %% Core Dimensions (shape-dependent)
    if strcmp(centerpost_shape, 'round')
        l_core = 2 * w_height + 2 * l_leg + 2 * r_centerpost;  % [m] total core length
    else
        l_core = 2 * w_height + 2 * l_leg + w_core;            % [m] total core length
    end
    
    h_core = 2 * h_yoke + params.w_b;

    %% Absolute height constraint
    if h_core > h_core_max
        result = struct( ...
            'is_valid',          false, ...
            'fail_reason',       'h_core exceeds h_core_max', ...
            'centerpost_shape',  centerpost_shape, ...
            'Bmax',              NaN, ...
            'Ac',                NaN, ...
            'r_centerpost',      r_centerpost, ...
            'w_core',            NaN, ...
            'l_leg',             NaN, ...
            'h_yoke',            NaN, ...
            'l_core',            NaN, ...
            'h_core',            h_core, ...
            'w_b',               params.w_b, ...
            'l_winding',         NaN, ...
            'w_winding',         NaN, ...
            'V_total',           NaN, ...
            'A_footprint',       NaN, ...
            'lg',                NaN, ...
            'Rdc_pri',           NaN, ...
            'Rdc_sec',           NaN, ...
            'P_core',            NaN, ...
            'P_pri',             NaN, ...
            'P_sec',             NaN, ...
            'P_total',           NaN, ...
            'T_tx',              NaN ...
        );
        return;
    end

    %% Winding Geometry (shape-dependent)
    if strcmp(centerpost_shape, 'round')
        l_winding = 2 * r_centerpost + 2 * w_height;                      % [m] winding outer length
        w_winding = 2 * r_centerpost + params.w_scale * 2 * w_height;     % [m] winding outer width
    else
        l_winding = w_core + 2 * w_height;                                % [m] winding outer length
        w_winding = w_core + params.w_scale * 2 * w_height;               % [m] winding outer width
    end

    %% Core Areas (shape-dependent)
    if strcmp(centerpost_shape, 'round')
        A_centerpost = pi * r_centerpost^2;        % [m^2] circular cross-section
    else
        A_centerpost = w_core^2;                   % [m^2] square cross-section
    end
    
    A_leg        = l_leg  * w_core;
    A_yoke       = h_yoke * w_core;
    A_footprint  = w_winding * l_core;

    %% Core Volumes
    V_centerpost = A_centerpost * params.w_b;
    V_legs       = 2 * A_leg  * params.w_b;
    V_yokes      = 2 * A_yoke * l_core;
    V_total      = V_centerpost + V_legs + V_yokes;

    %% Core Loss
    P_core = V_total * params.k * params.f^params.alpha * Bmax^params.beta;

    %% DC Resistance (shape-dependent)
    if strcmp(centerpost_shape, 'round')
        % Round winding: annular geometry
        % Inner radius = centerpost radius
        % Outer radius = centerpost radius + window height
        r_inner = r_centerpost;
        r_outer = r_centerpost + w_height;
        
        Rdc_pri = calculate_Rdc_round(100, ...
            r_inner, r_outer, ...
            params.sigma_cu, params.t_cu_pri);

        Rdc_sec = calculate_Rdc_round(100, ...
            r_inner, r_outer, ...
            params.sigma_cu, params.t_cu_sec);
    else
        % Square winding: rectangular geometry
        Rdc_pri = calculate_Rdc_rectangle(100, ...
            w_core, l_winding, ...
            w_core, w_winding, ...
            params.sigma_cu, params.t_cu_pri);

        Rdc_sec = calculate_Rdc_rectangle(100, ...
            w_core, l_winding, ...
            w_core, w_winding, ...
            params.sigma_cu, params.t_cu_sec);
    end

    %% AC Copper Loss
    [P_pri, P_sec] = calculate_Pcond( ...
        params.I, params.f, ...
        Rdc_pri, Rdc_sec, ...
        params.t_cu_pri, params.t_cu_sec, ...
        params.rho_cu, params.u0, params.stackup);

    %% Total Loss
    P_total = P_core + P_pri + P_sec;

    %% Temperature
    T_tx = calculate_transformer_temp( ...
        P_total, ...        % total dissipation
        Ac, ...             % center post area
        h_core/2, ...       
        R_plate, ...
        Area_plate, ...
        T_water, ...
        sig_grease, ...
        d_grease);

    %% Temperature constraint
    if T_tx > T_tx_max
        result = struct( ...
            'is_valid',          false, ...
            'fail_reason',       'T_tx exceeds T_tx_max', ...
            'centerpost_shape',  centerpost_shape, ...
            'Bmax',              NaN, ...
            'Ac',                Ac, ...
            'r_centerpost',      r_centerpost, ...
            'w_core',            w_core, ...
            'l_leg',             l_leg, ...
            'h_yoke',            h_yoke, ...
            'l_core',            l_core, ...
            'h_core',            h_core, ...
            'w_b',               params.w_b, ...
            'l_winding',         l_winding, ...
            'w_winding',         w_winding, ...
            'V_total',           V_total, ...
            'A_footprint',       A_footprint, ...
            'lg',                lg, ...
            'Rdc_pri',           Rdc_pri, ...
            'Rdc_sec',           Rdc_sec, ...
            'P_core',            P_core, ...
            'P_pri',             P_pri, ...
            'P_sec',             P_sec, ...
            'P_total',           NaN, ...
            'T_tx',              T_tx ...
        );
        return;
    end

    %% Package Results
    result = struct( ...
        'is_valid',          true, ...
        'fail_reason',       '', ...
        'centerpost_shape',  centerpost_shape, ...
        'Bmax',              Bmax, ...
        'Ac',                Ac, ...
        'r_centerpost',      r_centerpost, ...
        'w_core',            w_core, ...
        'l_leg',             l_leg, ...
        'h_yoke',            h_yoke, ...
        'l_core',            l_core, ...
        'h_core',            h_core, ...
        'w_b',               params.w_b, ...
        'l_winding',         l_winding, ...
        'w_winding',         w_winding, ...
        'V_total',           V_total, ...
        'A_footprint',       A_footprint, ...
        'lg',                lg, ...
        'Rdc_pri',           Rdc_pri, ...
        'Rdc_sec',           Rdc_sec, ...
        'P_core',            P_core, ...
        'P_pri',             P_pri, ...
        'P_sec',             P_sec, ...
        'P_total',           P_total, ...
        'T_tx',              T_tx ...
    );

end