function VIRT3Dfigure_square(result, material, T_tx, idx)
    figure(1)
    % --- Select subplot based on idx ---
    if idx == ~0
        subplot(2, 1, idx);
    end 
    cla;  % Clear current axes instead of clf
    hold on;
    axis equal;
    view(35, 15);
    grid on;
    grid minor;
    box on;

    % --- Colors ---
    core_color = [0.5, 0.5, 0.8];
    copper_pri = [0.85, 0.45, 0.01];

   a = result.a * 1e3; 
   b = result.b * 1e3; 
   w = result.w * 1e3; 
   s_ct = result.s_ct * 1e3; 
   h_pcb = result.h_pcb * 1e3; 
   lg = result.lg * 1e3; 
   centerpost_shape = 'square';

   w_winding = w - 2*s_ct;
   h_w = w/4 + h_pcb;
   w_tot = 2*w + 2*b;
   l = a + 2*w_winding + 2*s_ct;
   h = h_w + b;
   

    % --- Bottom Yoke ---
    drawBox([0, 0, 0], [w_tot, a, b/2], core_color);

    % --- Top Yoke ---
    drawBox([0, 0, b/2+h_w], [w_tot, a, b/2], core_color);

    % --- Left Leg ---
    drawBox([0, 0, 0], [b/2, a, h], core_color);

    % --- Right Leg ---
    drawBox([w_tot - b/2, 0, 0], [b/2, a, h], core_color);

   % --- Centerpost ---
        drawBox([b/2 + w, 0, 0], [b, a, b/2+h_w-lg], core_color);

    % --- Winding ---
 
    drawBox([b/2+s_ct, -w_winding - s_ct,  h/2-h_pcb/2], ...
            [w_tot - b - 2 * s_ct, w_winding , h_pcb], copper_pri);
    drawBox([b/2+s_ct, a + s_ct,  h/2-h_pcb/2], ...
            [w_tot - b - 2 * s_ct, w_winding , h_pcb], copper_pri);
    drawBox([b/2+s_ct, -w_winding - s_ct,  h/2-h_pcb/2], ...
            [w_winding, l , h_pcb], copper_pri);
    drawBox([b + w + b/2+s_ct, -w_winding - s_ct,  h/2-h_pcb/2], ...
            [w_winding, l , h_pcb], copper_pri);
  
    % --- Formatting ---
    xlabel('X [mm]', 'FontSize', 12, 'FontWeight', 'bold');
    ylabel('Y [mm]', 'FontSize', 12, 'FontWeight', 'bold');
    zlabel('Z [mm]', 'FontSize', 12, 'FontWeight', 'bold');
    
    title_str = sprintf(['3D EQ-Core Transformer (%s centerpost) - %s\n' ...
                         'P_v = %.0f kW/m³,  Footprint Area = %.1f mm^2,  Total Loss = %.2f W\n' ...
                         'Copper Loss = %.2f W,  Core Loss = %.2f W\n' ...
                         'Temp = %.2f °C'], ...
                        centerpost_shape, ...
                        material.name, ...
                        result.Pv, ...
                        result.A_footprint * 1e6, ...
                        result.P_total, ...
                        result.P_pri + result.P_sec, ...
                        result.P_core, ...
                        T_tx);
    title(title_str, 'FontSize', 13, 'FontWeight', 'bold');

    % --- Add textbox with design parameters ---
    info_str = sprintf([ ...
        '\\bf{Losses}\\rm\n' ...
        'P_{pri}    = %.3f W\n' ...
        'P_{sec}    = %.3f W\n' ...
        'P_{core}   = %.3f W\n' ...
        'P_{total}  = %.3f W\n' ...
        '\n\\bf{Geometry}\\rm\n' ... 
        'w_{tot} [X]       = %.2f mm\n' ...
        'w_{winding}       = %.2f mm\n' ...
        'l_{tot}[Y]        = %.2f mm\n' ...
        'l_{core}          = %.2f mm\n' ...
        'h_{core} [Z]      = %.2f mm'], ...
        result.P_pri, ...
        result.P_sec, ...
        result.P_core, ...
        result.P_total, ...
        result.w_tot * 1e3, ...
        result.w_winding * 1e3, ...
        result.l * 1e3, ...
        result.a * 1e3, ...
        result.h * 1e3);
     % 'b          = %.2f mm\n' ...
        % 'w          = %.2f mm\n' ...
        %result.b * 1e3, ...
        %result.w * 1e3, ...
        
    
    annotation('textbox', [0.75, 0.3, 0.2, 0.4], ...
        'String', info_str, ...
        'FontSize', 10, ...
        'FontName', 'FixedWidth', ...
        'EdgeColor', 'k', ...
        'BackgroundColor', 'w', ...
        'FitBoxToText', 'on', ...
        'Interpreter', 'tex');

    rotate3d on;
    hold off;

end